language: php
php:
  - 5.3
  - 5.4
branches:
  only:
    - master
before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar update
script: phpunit -c phpunit.xml.travisci --coverage-text