language: php
php:
  - 5.3
  - 5.4
branches:
  only:
    - master
before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar update
notifications:
  webhooks:
    urls:
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_start: true
script: phpunit -c phpunit.xml.travisci --coverage-text